name: Scrape latest vgc data

on:
  workflow_dispatch:
  schedule:
    - cron: '42 6-22 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies and scrape vgc
        run: npm install && npm run vgc
      - name: Commit and push if it changed
        id: try-commit-push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest vgc data: ${timestamp}" || exit 0
          git push
          additions="$(git diff HEAD^ HEAD --no-ext-diff --unified=0 --exit-code -a --no-prefix ':*.md' | egrep '^\+\+\+' | sed -r 's/\+\+\+ (.*)/[\1]\(https\:\/\/github\.com\/chiviteam\/vgc-alerts\/blob\/main\/\1\)/' | tr '\n' ' ')"
          echo "::set-output name=vgc-additions::$additions"
      - name: Wire Error Message
        uses: wireapp/github-action-wire-messenger@v1
        if: ${{ failure() }}
        with:
          email: ${{secrets.WIRE_EMAIL}}
          password: ${{secrets.WIRE_PASSWORD}}
          conversation: ${{secrets.WIRE_CONVERSATION}}
          text: "Vgc alert - something went wrong: [Check this](https://github.com/chiviteam/vgc-alerts/actions)"
      - name: Wire Messenger
        uses: wireapp/github-action-wire-messenger@v1
        if: ${{ success() && steps.try-commit-push.outputs.vgc-additions != ''}}
        with:
          email: ${{secrets.WIRE_EMAIL}}
          password: ${{secrets.WIRE_PASSWORD}}
          conversation: ${{secrets.WIRE_CONVERSATION}}
          text: "Vgc alert - new additions: ${{steps.try-commit-push.outputs.vgc-additions}}"