name: Send messages to Wire on changes

on:
  push:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Wire Messenger
        uses: wireapp/github-action-wire-messenger@v1
        with:
          email: ${{secrets.WIRE_EMAIL}}
          password: ${{secrets.WIRE_PASSWORD}}
          conversation: ${{secrets.WIRE_CONVERSATION}}
          text: 'Vgc alert: something changed : [See latest commit](https://github.com/chiviteam/vgc-alerts/commits/main)'
